---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
Mat1 <- matrix(c(1:6),2,3)
Mat1
```

```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]

```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF
```


```{r}
class(StuDF)
typeof(StuDF)
```

```{r}
StuDF[[2]][[3]]
```
```{r}
class(StuDF$姓名)
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
as.data.frame(StuList) -> StuDF3

class(StuDF3)
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

```{r}
chosenLETTERS <- LETTERS[4:15]
matObj1 <- matrix(chosenLETTERS,4,3)
matObj1
tolower(matObj1)
toupper(matObj1)
matObj1[[5]]
```
```{r}
matObj1[c(1,3),c(1,2)]
matObj1[c(T,F,F,F),c(T,F,F)]
```











































