---
title: '2019-05-22'
author: "陳品瑄"
date: "5/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
load("C:/Users/Pin Syuan Chen/Desktop/git/pinbaby/107-2-inclass-practice/invoiceList.Rda")

names(invoiceList) <-
  c('訂單時區','訂單時間(以訂單時區顯示)','UTC時間')
```

```{r}
library(lubridate)
(invoiceList$訂單時區=="America/New_York") -> nyLogical
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical

invoiceList$UTC時間[nyLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical],
          tz="America/New_York"),tzone="UTC")
invoiceList$UTC時間[tpLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei"),tzone="UTC")

invoiceList 
```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```

```{r}
tt <- (invoiceList$訂單時區=="Asia/Taipei")

invoiceList$tt <- tt

invoiceList$UTC時間[tt] <- with_tz(ymd_hms(invoiceList$訂單時區之下單時間[tt],tz="Asia/Taipei"),tz="UTC")

```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```
#請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示。
```{r}
date <-ymd_hms("1973-02-21 12:05:22",tz="America/New_York")
change <-with_tz(date,tz="Asia/Taipei")
```

```{r}
ymd_hms_tzChange <-function(input,fromTzone,toTzone){
  answer <- with_tz(ymd_hms(input,tz=fromTzone),tzone=toTzone)
   return(answer)}

```

```{r}
date_convert_twYM <- function(x){
yyyy<-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(x,"[:digit:]+(?=月)")
answer<- ymd(str_c(yyyy,mm,"01",sep="-"))
return(answer)
}
```


```{r}
#沒有預設值

date_convert_twYM <- function(twDates){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}
#有預設值

date_convert_twYM <- function(twDates,dd="01"){
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  yyyymmdd
}
```









































