---
title: '2019-05-29'
author: "陳品瑄"
date: "5/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
browseURL("https://www.ntpu.edu.tw")
```


```{r}
now <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
textbookURL<-function(){
browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#section-8.1")}
textbookURL()
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}


```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  Qs<-a+b*P
  Qd<-c-d*P
  Excess <- Qs-Qd
  return(list(QS=供給量,Qd=需求量,Excess=超額供給量))
}
```
```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```

```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID %in% transcriptDataFinal$學號){
  return(GPA)
  }else{
      message("查無此學號")
    }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
_

```

```{r}
gpa_fun <- function(studentID){

  if(studentID %in% transcriptDataFinal$學號){
    transcriptDataFinal$學號==studentID -> logiChosenStudent

    subSample <- transcriptDataFinal[logiChosenStudent,]

    sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
    return(GPA)
  }else{
    message("查無此學號")

 }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```


```{r}
a <- readline(prompt = "請輸入一個數字： ")
a
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

```{r}
fizzbuzz <- function(num){if(num%%3==0&num%%5!=0){print("fizz")}ifelse(num%%5==0&num%%3!=0){print("buzz")}else(num%%3==0&num%%5==0){fizzbuzz}}
```

```{r}
fizzbuzz<-function(a){

  if(a%%3==0 & a%%5==0)
    {print("fizzbuzz")}
  else if(a%%3==0)
     {print("fizz")}
  else if(a%%5==0)
     {print("buzz")}
  else{print(a)}
 }
```

```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
```





























