---
title: '2019-03-27'
author: "陳品瑄"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 

```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)

```

```{r}
class(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
AraguainaDateTime <- with_tz(twDateTime,tzone="America/Araguaina")
```

```{r}
typeof(AraguainaDateTime)
```

```{r}
as.double(AraguainaDateTime)
as.double(twDateTime)
```

```{r}
twDateTime <- mdy_hms("3/14/2019 8:18:47")
```

```{r}
twDateTime <- ymd("2018-09-11")
```

```{r}
twDateTime <- mdy("March 3, 2019")
```

```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```


```{r}
a+bL
class(a+bL)
```

```{r}
aL+bL
class(aL+bL)
```

```{r}
aL-bL
class(aL-bL)
```

```{r}
aL-b
class(aL-b)
```

