---
title: '2019-05-08'
author: "pin"
date: "5/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
x <- as.character(round(runif(10)*100),10)
x
```

```{r}
library(lubridate); library(stringr); library(dplyr); library(readr); library(purrr)
```



考試1.
```{r}
class(x)
logicBig <- (as.integer(x) > 50)
logicBig
typeof(x)
```

5.
```{r}

sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
twDates
```
5.1 去除字元
請將twDates中的“民國”及“月”都去除，並存在twDates2答案物件，如：“民國099年2月”會變成“099年2”
```{r}
twDates2 <- str_replace_all(twDates,"(民國)|(月)","")
twDates2
```

```{r}
str_replace(twDates,"民國","") -> twDates3
str_replace(twDates2,"月","") -> twDates3
str_replace_all(twDates,"(民國)|(月)","")
twDates3
```
```{r}
westYears <- as.integer(str_sub(twDates,3,5))+1911
westYears
```

5.3
```{r}
mm <- str_split(twDates2,"年")
month <- map(mm,~.[[2]])
unlist(month)
year <-westYears
westDates <- ymd(str_c(year,month,"01",sep = "-"))
westDates
```

##6
6
```{r}
load("invoiceList.Rda")
str(invoiceList)
names(invoiceList) <-
  c('訂單時區','訂單時間(以訂單時區顯示)','UTC時間')
```
```{r}

```


##7
```{r}
load("dsampledTranscriptData.Ra")
names(sampledTranscriptData) <- 
  c('學號','學期成績','學分數','學年','學期','必選修類別（必／選／通）','系級','科目名稱','年級','學屆')
```

7.3 產生學系 str_replace_all
請在sampledTranscriptData新增一個「學系」變數，存在sampledTranscriptData$學系答案物件裡，它是「系級」元素值去除數字1,2,3,4的結果。例如：系級為“經濟學系2”, 學系值即為“經濟學系”。（hint: 可透過str_replace()或str_replace_all()把字串中的數字去除。）
```{r}
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$系級,"1","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"2","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"3","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"4","")
str_replace(sampledTranscriptData,"[:digit:]","")

sampledTranscriptData$學系 
```

```{r}
(sampledTranscriptData$系碼!="73" & 
   sampledTranscriptData$學系=="經濟學系") -> logiCheck
sampledTranscriptData$學號[logiCheck] %>% unique() -> changeMajorStudent

changeMajorStudent
```











